name = "daily-notes"
main = "src/index.ts"
compatibility_date = "2025-11-07"

# Observability (Logs / Metrics)
[observability]
enabled = true

# Cron triggers
[triggers]
crons = ["5 0 * * *", "10 0 * * *", "10 16 * * *"]

# -------------------------------------------------------
# Environment Variables
# Uncomment and add variables if needed.
# [vars]
# MY_VARIABLE = "production_value"

# -------------------------------------------------------
# Static assets
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# -------------------------------------------------------
# Service Bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# -------------------------------------------------------
# Smart Placement
# [placement]
# mode = "smart"