name = "daily-notes"
main = "src/index.ts"
compatibility_date = "2025-11-07"

# Observability (Logs / Metrics)
[observability]
enabled = true

# Cron triggers
[triggers]
crons = ["5 */4 * * *"]

# KV Bindings
[[kv_namespaces]]
binding = "DAILY_NOTES_KV"
id = "91fee2d4a73f4462bb7de4ad6d1f1d46"

# -------------------------------------------------------
# Environment Variables
# Uncomment and add variables if needed.
# [vars]
# MY_VARIABLE = "production_value"

# -------------------------------------------------------
# Static assets
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# -------------------------------------------------------
# Service Bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# -------------------------------------------------------
# Smart Placement
# [placement]
# mode = "smart"